name: Container Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-container-build.yml@main
    with:
      image_name: sample-api
      image_tag: ${{ github.run_id }}
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # MEND_API_KEY: ${{ secrets.MEND_API_KEY }}
      # MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
      # MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
