name: Container Deploy

on:
  workflow_run:
    workflows: ["Container Build"]
    types: [completed]

  workflow_dispatch:
    inputs:
      buildRunId:
        required: true
        type: string
        
permissions:
  id-token: write
  contents: read 
  
jobs:
  deploy_to_dev:
    if: startsWith(github.event.workflow_run.head_branch, 'dev') && github.event.workflow_run.conclusion == 'success'
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-container-deploy.yml@main
    with:
      image_name: sample-api
      image_tag: ${{ github.event.workflow_run.head_sha }}
      acr_name: myacr
      container_app_name: sample-api
      resource_group: rg-containers
      buildRunId: ${{ github.event.workflow_run.id || inputs.buildRunId }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
  deploy_to_uat:
    if: startsWith(github.event.workflow_run.head_branch, 'uat') && github.event.workflow_run.conclusion == 'success'
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-container-deploy.yml@main
    with:
      image_name: sample-api
      image_tag: ${{ github.event.workflow_run.head_sha }}
      acr_name: myacr
      container_app_name: sample-api
      resource_group: rg-containers
      buildRunId: ${{ github.event.workflow_run.id || inputs.buildRunId }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    

      
  deploy_to_prod:
    if: github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.conclusion == 'success'
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-container-deploy.yml@main
    with:
      image_name: sample-api
      image_tag: ${{ github.event.workflow_run.head_sha }}
      acr_name: myacr
      container_app_name: sample-api
      resource_group: rg-containers
      buildRunId: ${{ github.event.workflow_run.id || inputs.buildRunId }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    
      
