name: Container Build (caller)

on:
    workflow_dispatch:

env:
    IMAGE_NAME: mydockerimage
    IMAGE_TAG: ${{ github.run_id }}
    DOCKERFILE_PATH: Dockerfile


jobs:
    call-container-build:
        uses: ./.github/workflows/template-container-build.yml
        with:
            image_name: $IMAGE_NAME 
            image_tag: $IMAGE_TAG
            dockerfile_path: $DOCKERFILE_PATH