name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  destroy:
    uses: ./.github/workflows/reusable-terraform-plan-destroy.yml
    with:
      terraform-version: 'latest'
      environment-path: 'environments/dev01'
      backend-storage-account: 'adoterraformstate'
      backend-container-name: 'terraform'
      backend-state-key: 'poc.tfstate'
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      source-artifact-name: 'terraform-source-${{ github.run_number }}'  # Reference a prior build artifact
      environment-name: 'dev01'  # Use environment with strict approvers
    secrets: inherit