name: Terraform single workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env: 
  TF_WORKING_DIR: terraform-build-and-deploy/environments/dev01
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-dev01
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init -input=false  \
          -backend-config="use_azuread_auth=true" \
          -backend-config="storage_account_name=terrafromtfstate" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=environments/dev01/terraform.tfstate"

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate 

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Add Terraform plan to summary
        run: |
          echo "## Terraform Plan ${{ github.runid }} >> $GITHUB_STEP_SUMMARY
          terraform show tfplan >> $GITHUB_STEP_SUMMARY
