name: Terraform Deploy

run-name: ${{ github.run_id }}

on: 
  workflow_run:
    types: ['completed']
    workflows: [Terraform Build]

  workflow_dispatch:
    inputs:
      buildRunId:
        type: string
        required: true

jobs:
  Terraform-Deploy:
    uses: dpdeepankar/GithubActionsTest/.github/workflows/template-tf-deploy.yml@main
    with:
     buildRunId: ${{ github.events.workflow_run.id || inputs.buildRunId }}
     workingDirectory: terraform-build-and-deploy/environments/dev01
     backendStorageAccount: terrafromtfstate
     backendContainerName: tfstate
     backendKey: dev01.tfstate
     backendResourceGroup: devopsmi-rg
    secrets:
     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
