name: terraform-destroy-manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (e.g., dev01)'
        required: true
        default: dev01

jobs:
  destroy:
    uses: ./.github/workflows/terraform-destroy-template.yml
    with:
      environmentPath: 'environments/${{ github.event.inputs.environment }}'
      terraformVersion: 'latest'
      backendStorageAccount: 'adoterraformstate'
      backendContainerName: 'terraform'
      backendStateKey: 'poc.tfstate'
      azureSubscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      environment: 'dev01-destroy'  # ek dedicated GitHub environment jisme heavy approvals
