name: Terraform Build Pipeline

run-name: ${{ github.ref_name }}-${{ github.run_id }}

on:
  workflow_dispatch:
    inputs:
      # appEnvironment: 
      #   description: 'target environment to build'
      #   required: true
      #   type: choice
      #   options:
      #    - dev01
      #    - dev02
      #    - dev03
      targetEnvironment:
        description: 'app environment'
        required: true
        type: choice
        options:
         - dev
         - dlv
         - acc
         - prod

env:
  BACKEND_STORAGE_ACCOUNT: "abcd"
  BACKEND_CONTAINER_NAME: "terraform"
  BACKEND_KEY: "terraform.tfstate"
  BACKEND_RESOURCE_GROUP: "rg1"
  WORKING_DIR: "terraform-build-and-deploy/environments/dev01"
  WORKFLOW_ENVIRONMENT: 'poc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout self
       uses: actions/checkout@v4

     - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: drop
         path: ${{ github.workspace }}

     - name: Create config
       run: |
        cat <<EOF > config.json
        {
            "targetEnvironment": "${{ inputs.targetEnvironment }}",
            "backendStorageAccount" : "${{ env.BACKED_STORAGE_ACCOUNT }}",
            "backendContainerName": "${{ env.BACKEND_CONTAINER_NAME }}",
            "backendResourceGroup": "${{ env.BACKEND_RESOURCE_GROUP }}",
            "backendKey": "${{ env.BACKEND_KEY }}",
            "workflowEnvironment": "${{ env.WORKFLOW_ENVIRONMENT }}",
            "workingDirectory": "${{ env.WORKING_DIR }}
        }
        EOF

     - name: Upload config as artifact
       uses: actions/upload-artifact@v4
       with:
         name: config.json
         path: config.json

     - name: Add build summary
       run: |
         echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
         echo "Run ID: ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
         echo "Branch: ${{ gitub.ref_name }}" >> $GITHUB_STEP_SUMMARY
         echo "commit sha: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY 

 
